spring.application.name=lawfirm-api
server.forward-headers-strategy=framework
#setup postgres db
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/lawfirm_db
#spring.datasource.username=postgres
#spring.datasource.password=123
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/lawfirm_db
spring.datasource.username=postgres
spring.datasource.password=123
#basic auth security
spring.security.user.name=me
spring.security.user.password=123
spring.jpa.hibernate.ddl-auto=update


#minio port

minio.url=http://localhost:9000
minio.access.name=admin
minio.access.secret=@Password123!
minio.bucket.name=lawfirm-bucket


spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB